[workspace]
resolver = "2"
members = [
    "forc",
    "forc-pkg",
    "forc-plugins/forc-client",
    "forc-plugins/forc-crypto",
    "forc-plugins/forc-doc",
    "forc-plugins/forc-fmt",
    "forc-plugins/forc-lsp",
    "forc-plugins/forc-tx",
    "forc-test",
    "forc-tracing",
    "forc-util",
    "scripts/mdbook-forc-documenter",
    "sway-ast",
    "sway-core",
    "sway-error",
    "sway-ir",
    "sway-ir/sway-ir-macros",
    "sway-lsp",
    "sway-parse",
    "sway-types",
    "sway-utils",
    "swayfmt",
    "test",
]
exclude = [
    "examples/*",
    "swayfmt/test_macros",
    "forc-test/test_data"
]

[workspace.dependencies]
# Dependencies from the `fuel-core` repository:
fuel-core-client = { version = "0.20.3", default-features = false }

# Dependencies from the `fuel-vm` repository:
fuel-asm = { git = "https://github.com/FuelLabs/fuel-vm/", branch = "master" }
fuel-crypto = { git = "https://github.com/FuelLabs/fuel-vm/", branch = "master" }
fuel-types = { git = "https://github.com/FuelLabs/fuel-vm/", branch = "master" }
fuel-tx = { git = "https://github.com/FuelLabs/fuel-vm/", branch = "master" }
fuel-vm = { git = "https://github.com/FuelLabs/fuel-vm/", branch = "master" }


# Dependencies from the `fuels-rs` repository:
fuels-core = "0.45"
fuels-accounts = "0.45"

# Dependencies from the `forc-wallet` repository:
forc-wallet = "0.2.5"

[workspace.package]
edition = "2021"
authors = ["Fuel Labs <contact@fuel.sh>"]
homepage = "https://fuel.network/"
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/sway"

[patch.crates-io]
# Keep it until release of the `fuel-core`.
fuel-core-client = { git = "https://github.com/FuelLabs/fuel-core", branch = "master" }

# Keep it until release of the `fuels-rs`.
fuels-core = { git = "https://github.com/FuelLabs/fuels-rs", branch = "hal3e/transaction-policies" }
fuels-accounts = { git = "https://github.com/FuelLabs/fuels-rs", branch = "hal3e/transaction-policies" }

# Keep it until release of the `forc-wallet`.
forc-wallet = { git = "https://github.com/FuelLabs/forc-wallet", branch = "upgrade/fuel-core-master" }
fuels = { git = "https://github.com/FuelLabs/fuels-rs", branch = "hal3e/transaction-policies" }

fuel-asm = { git = "https://github.com/FuelLabs/fuel-vm/", branch = "master" }
fuel-crypto = { git = "https://github.com/FuelLabs/fuel-vm/", branch = "master" }
fuel-types = { git = "https://github.com/FuelLabs/fuel-vm/", branch = "master" }
fuel-tx = { git = "https://github.com/FuelLabs/fuel-vm/", branch = "master" }
fuel-vm = { git = "https://github.com/FuelLabs/fuel-vm/", branch = "master" }
